/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yoon.pms;

public class ClientApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ClientApp().getGreeting());
    }
}
